#include "src/game/envfx_snow.h"

const GeoLayout pirate_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(1, 0, -67, 0, 15, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 85, 89, -14, -123, -65, -26),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(1, -84, 89, -14, 120, -99, -13),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 65, -17, -10, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, pirate_body_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 49, 54, 8, 0, 8, -57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, pirate_arm_L_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 42, 0, -62, -90, -7),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, pirate_Hand_L_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, -49, 54, 8, -25, 9, 53),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, pirate_arm_R_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 42, 0, 60, -136, -22),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, pirate_Hand_R_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, 27, 54, 4, 6, 13, -176),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 69, 0, -74, 21, 162),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, pirate_foot_L_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, -27, 54, 4, 7, 14, 179),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 69, 0, -74, 6, -162),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, pirate_foot_R_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 88, 0, -5, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, pirate_head_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, pirate_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, pirate_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, pirate_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, pirate_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, pirate_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, pirate_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, pirate_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, pirate_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
