#include "src/game/envfx_snow.h"

const GeoLayout hypno_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 42, 0, hypno_lombar_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_chest_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, 17, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_chest_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_head_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 39, 0, 3, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_head_mesh),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_upArm_L_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 25, 27, -6, -106, 3, -90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_upArm_L_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_downArm_L_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 26, 0, 4, 3, -9),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_downArm_L_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_hand_L_skinned),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, -3, -4, 7),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_hand_L_mesh),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_thumb2_L_skinned),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 17, 14, -7, -55, -130, 64),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_thumb2_L_mesh),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_toes_L_skinned),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 15, 0, -9, -16, 1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_toes_L_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_upArm_R_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -25, 27, -6, -106, -3, 90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_upArm_R_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_downArm_R_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 26, 0, 4, -3, 9),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_downArm_R_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_hand_R_skinned),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 28, 0, -3, 4, -7),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_hand_R_mesh),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, 18, -8, -2, 91, -92),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_item_mesh),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_thumb2_R_skinned),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -17, 14, -7, -55, 130, -64),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_thumb2_R_mesh),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_toes_R_skinned),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 15, 0, -9, 16, -1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_toes_R_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_upLeg_L_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 12, 3, 161, -6, -6),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_upLeg_L_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_downLeg_L_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, 0, 32, -3, 5),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_downLeg_L_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_foot_L_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, 7, -93, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_foot_L_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_upLeg_R_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -16, 12, 3, 161, 6, 6),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_upLeg_R_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_downLeg_R_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, 0, 32, 3, -5),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_downLeg_R_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_foot_R_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, 7, -93, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hypno_foot_R_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, hypno_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
