extern const GeoLayout jellyblock_geo_opt_1[];
extern const GeoLayout jellyblock_geo_opt_2[];
extern const GeoLayout jellyblock_geo[];
extern u8 jellyblock_fx_377_tex_rgba32[];
extern u8 jellyblock_Upsetti_Neutral_ia8[];
extern u8 jellyblock_Upsetti_ia8_ia8[];
extern u8 jellyblock_Moan_ia8_ia8[];
extern Vtx jellyblock_Bone_mesh_layer_5_vtx_0[29];
extern Gfx jellyblock_Bone_mesh_layer_5_tri_0[];
extern Vtx jellyblock_Bone_002_mesh_layer_4_vtx_0[4];
extern Gfx jellyblock_Bone_002_mesh_layer_4_tri_0[];
extern Gfx mat_jellyblock_f3d_material_042[];
extern Gfx mat_revert_jellyblock_f3d_material_042[];
extern Gfx mat_jellyblock_f3dlite_material_002[];
extern Gfx mat_revert_jellyblock_f3dlite_material_002[];
extern Gfx mat_jellyblock_f3dlite_material_001[];
extern Gfx mat_revert_jellyblock_f3dlite_material_001[];
extern Gfx mat_jellyblock_f3dlite_material[];
extern Gfx mat_revert_jellyblock_f3dlite_material[];
extern Gfx jellyblock_Bone_mesh_layer_5[];
extern Gfx jellyblock_Bone_002_mesh_layer_4[];
extern Gfx jellyblock_Bone_002_mesh_layer_4_opt_1_with_layer_4_revert[];
extern Gfx jellyblock_Bone_002_mesh_layer_4_opt_2_with_layer_4_revert[];
