#include "src/game/envfx_snow.h"

const GeoLayout stingby_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 5, 90, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, stingby_body_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, stingby_body_mesh_layer_6),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 17, -20, 27, 131, 0, -11),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, stingby_leg_L_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -17, -20, 27, 131, 0, 11),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, stingby_leg_R_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, stingby_wing_L_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 33, -3, -19, 5, -143, 90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, stingby_wing_L_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, stingby_wing_R_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -33, -3, -19, 5, 143, -90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, stingby_wing_R_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, stingby_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, stingby_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, stingby_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
