extern const GeoLayout redthwomp_Bone_opt1[];
extern const GeoLayout redthwomp_Bone_opt2[];
extern const GeoLayout redthwomp_Bone_opt3[];
extern const GeoLayout redthwomp_Bone_opt4[];
extern const GeoLayout redthwomp_Bone_opt5[];
extern const GeoLayout redthwomp_Bone_opt6[];
extern const GeoLayout redthwomp_Bone_opt7[];
extern const GeoLayout redthwomp_geo[];
extern Lights1 redthwomp_RedPattern_v4_lights;
extern Lights1 redthwomp_K_Diamonds_v4_lights;
extern Lights1 redthwomp_Q_Diamonds_v4_lights;
extern Lights1 redthwomp_J_Diamond_v4_lights;
extern Lights1 redthwomp_A_Diamond_v4_lights;
extern Lights1 redthwomp_K_Hearts_v4_lights;
extern Lights1 redthwomp_Q_Hearts_v4_lights;
extern Lights1 redthwomp_J_Hearts_v4_lights;
extern Lights1 redthwomp_A_Hearts_v4_lights;
extern u8 redthwomp_red_ci8[];
extern u8 redthwomp_red_ci8_pal_rgba16[];
extern u8 redthwomp_K_Diamond_ci4[];
extern u8 redthwomp_K_Diamond_ci4_pal_rgba16[];
extern u8 redthwomp_Q_Diamond_ci4[];
extern u8 redthwomp_Q_Diamond_ci4_pal_rgba16[];
extern u8 redthwomp_J_Diamond_ci4[];
extern u8 redthwomp_J_Diamond_ci4_pal_rgba16[];
extern u8 redthwomp_A_Diamond_ci4[];
extern u8 redthwomp_A_Diamond_ci4_pal_rgba16[];
extern u8 redthwomp_K_Heart_ci4[];
extern u8 redthwomp_K_Heart_ci4_pal_rgba16[];
extern u8 redthwomp_Q_Heart_ci4[];
extern u8 redthwomp_Q_Heart_ci4_pal_rgba16[];
extern u8 redthwomp_J_Heart_ci4[];
extern u8 redthwomp_J_Heart_ci4_pal_rgba16[];
extern u8 redthwomp_A_Heart_ci4[];
extern u8 redthwomp_A_Heart_ci4_pal_rgba16[];
extern Vtx redthwomp_Bone_001_mesh_layer_1_vtx_0[48];
extern Gfx redthwomp_Bone_001_mesh_layer_1_tri_0[];
extern Vtx redthwomp_Bone_001_mesh_layer_1_vtx_1[28];
extern Gfx redthwomp_Bone_001_mesh_layer_1_tri_1[];
extern Gfx mat_redthwomp_RedPattern_v4[];
extern Gfx mat_revert_redthwomp_RedPattern_v4[];
extern Gfx mat_redthwomp_K_Diamonds_v4[];
extern Gfx mat_revert_redthwomp_K_Diamonds_v4[];
extern Gfx mat_redthwomp_Q_Diamonds_v4[];
extern Gfx mat_revert_redthwomp_Q_Diamonds_v4[];
extern Gfx mat_redthwomp_J_Diamond_v4[];
extern Gfx mat_revert_redthwomp_J_Diamond_v4[];
extern Gfx mat_redthwomp_A_Diamond_v4[];
extern Gfx mat_revert_redthwomp_A_Diamond_v4[];
extern Gfx mat_redthwomp_K_Hearts_v4[];
extern Gfx mat_revert_redthwomp_K_Hearts_v4[];
extern Gfx mat_redthwomp_Q_Hearts_v4[];
extern Gfx mat_revert_redthwomp_Q_Hearts_v4[];
extern Gfx mat_redthwomp_J_Hearts_v4[];
extern Gfx mat_revert_redthwomp_J_Hearts_v4[];
extern Gfx mat_redthwomp_A_Hearts_v4[];
extern Gfx mat_revert_redthwomp_A_Hearts_v4[];
extern Gfx redthwomp_Bone_001_mesh_layer_1[];
extern Gfx redthwomp_Bone_001_mesh_layer_1_mat_override_Q_Diamonds_v4_0[];
extern Gfx redthwomp_Bone_001_mesh_layer_1_mat_override_J_Diamond_v4_1[];
extern Gfx redthwomp_Bone_001_mesh_layer_1_mat_override_A_Diamond_v4_2[];
extern Gfx redthwomp_Bone_001_mesh_layer_1_mat_override_K_Hearts_v4_3[];
extern Gfx redthwomp_Bone_001_mesh_layer_1_mat_override_Q_Hearts_v4_4[];
extern Gfx redthwomp_Bone_001_mesh_layer_1_mat_override_J_Hearts_v4_5[];
extern Gfx redthwomp_Bone_001_mesh_layer_1_mat_override_A_Hearts_v4_6[];
extern Gfx redthwomp_material_revert_render_settings[];
