extern const GeoLayout butler_geo[];
extern Vtx butler_body_mesh_vtx_0[109];
extern Gfx butler_body_mesh_tri_0[];
extern Vtx butler_body_mesh_vtx_1[5];
extern Gfx butler_body_mesh_tri_1[];
extern Vtx butler_arm_L_mesh_vtx_0[26];
extern Gfx butler_arm_L_mesh_tri_0[];
extern Vtx butler_arm_L_mesh_vtx_1[30];
extern Gfx butler_arm_L_mesh_tri_1[];
extern Vtx butler_arm_R_mesh_vtx_0[11];
extern Gfx butler_arm_R_mesh_tri_0[];
extern Vtx butler_arm2_R_mesh_vtx_0[9];
extern Gfx butler_arm2_R_mesh_tri_0[];
extern Vtx butler_arm2_R_mesh_vtx_1[30];
extern Gfx butler_arm2_R_mesh_tri_1[];
extern Vtx butler_arm2_R_mesh_vtx_2[4];
extern Gfx butler_arm2_R_mesh_tri_2[];
extern Vtx butler_arm2_R_skinned_vtx_0[13];
extern Gfx butler_arm2_R_skinned_tri_0[];
extern Vtx butler_head_mesh_vtx_0[109];
extern Gfx butler_head_mesh_tri_0[];
extern Vtx butler_head_mesh_vtx_1[51];
extern Gfx butler_head_mesh_tri_1[];
extern Vtx butler_foot_L_mesh_vtx_0[20];
extern Gfx butler_foot_L_mesh_tri_0[];
extern Vtx butler_foot_R_mesh_vtx_0[20];
extern Gfx butler_foot_R_mesh_tri_0[];

extern Gfx butler_body_mesh[];
extern Gfx butler_arm_L_mesh[];
extern Gfx butler_arm_R_mesh[];
extern Gfx butler_arm2_R_mesh[];
extern Gfx butler_arm2_R_skinned[];
extern Gfx butler_head_mesh[];
extern Gfx butler_foot_L_mesh[];
extern Gfx butler_foot_R_mesh[];
extern Gfx butler_material_revert_render_settings[];

