extern const GeoLayout treasuredoor_geo[];
extern Lights1 treasuredoor_f3d_material_006_layer1_lights;
extern u8 treasuredoor__0x5DC0_i4[];
extern u8 treasuredoor_Glover_3F542A37_0_0_53890F9D_ciByRGBA_i8[];
extern Vtx treasuredoor_world_006_mesh_layer_1_vtx_0[42];
extern Gfx treasuredoor_world_006_mesh_layer_1_tri_0[];
extern Gfx mat_treasuredoor_f3d_material_006_layer1[];
extern Gfx mat_revert_treasuredoor_f3d_material_006_layer1[];
extern Gfx treasuredoor_world_006_mesh_layer_1[];
extern Gfx treasuredoor_material_revert_render_settings[];
