#include "src/game/envfx_snow.h"

const GeoLayout jrb_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_bush1_3_003_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_Cube_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_pillar12_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_pillar12_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_poles_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_poles_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_poles_003_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_terrain_005_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 4304, 2826, 34719, 4304, 2825, 34719, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, jrb_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
