#include "src/game/envfx_snow.h"

const GeoLayout shyguycaptain_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, shyguycaptain_BODY_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_Bone_001_skinned_mesh_layer_5),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 100, 0, shyguycaptain_Bone_001_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_shoulder_l_skinned_mesh_layer_5),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 41, 78, 0, shyguycaptain_shoulder_l_mesh_layer_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_elbow_l_skinned_mesh_layer_5),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 32, 0, 0, shyguycaptain_elbow_l_mesh_layer_5),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 47, -8, 0, shyguycaptain_Bone_006_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, shyguycaptain_Bone_006_mesh_layer_4),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_shoulder_r_skinned_mesh_layer_5),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, -41, 78, 0, shyguycaptain_shoulder_r_mesh_layer_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_elbow_r_skinned_mesh_layer_5),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, -32, 0, 0, shyguycaptain_elbow_r_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
