#include "src/game/envfx_snow.h"

const GeoLayout staryu_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, -37, 4, staryu_center_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, staryu_down_L_skinned),
			GEO_TRANSLATE_ROTATE(1, 30, -3, -3, 0, 0, -155),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, staryu_down_L_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(1, staryu_down_R_skinned),
			GEO_TRANSLATE_ROTATE(1, -30, -3, -3, 0, 0, 155),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, staryu_down_R_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(1, staryu_top_skinned),
			GEO_ANIMATED_PART(1, 0, 86, -3, staryu_top_mesh),
			GEO_DISPLAY_LIST(1, staryu_up_L_skinned),
			GEO_TRANSLATE_ROTATE(1, 42, 54, -3, 0, 0, -83),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, staryu_up_L_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(1, staryu_up_R_skinned),
			GEO_TRANSLATE_ROTATE(1, -42, 54, -3, 0, 0, 83),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, staryu_up_R_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, staryu_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, staryu_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, staryu_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, staryu_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, staryu_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, staryu_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, staryu_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, staryu_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
