#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"
#include "levels/castle_grounds/leveldata.inc.c"

#include "levels/castle_grounds/panther/model.inc.c"
#include "levels/castle_grounds/dolphin/model.inc.c"
#include "levels/castle_grounds/raft/model.inc.c"
#include "levels/castle_grounds/jetski/model.inc.c"
#include "levels/castle_grounds/raft/collision.inc.c"
#include "levels/castle_grounds/jetski/collision.inc.c"
#include "levels/castle_grounds/pirateship/collision.inc.c"
#include "levels/castle_grounds/pirateship/model.inc.c"
#include "levels/castle_grounds/pirate/model.inc.c"
#include "levels/castle_grounds/cross/model.inc.c"

#include "levels/castle_grounds/panther/anims/data.inc.c"
#include "levels/castle_grounds/panther/anims/table.inc.c"
#include "levels/castle_grounds/dolphin/anims/data.inc.c"
#include "levels/castle_grounds/dolphin/anims/table.inc.c"
#include "levels/castle_grounds/flower/model.inc.c"
#include "levels/castle_grounds/toadlawyer/model.inc.c"
#include "levels/castle_grounds/toadlawyer/anims/data.inc.c"
#include "levels/castle_grounds/toadlawyer/anims/table.inc.c"
#include "levels/castle_grounds/treasuredoor/model.inc.c"
#include "levels/castle_grounds/treasuredoor/collision.inc.c"