extern const GeoLayout medusagate_geo[];
extern Lights1 medusagate_f3d_material_lights;
extern u8 medusagate_OSC_P_T_FENCE01_ia8[];
extern Vtx medusagate_Plane_mesh_layer_4_vtx_cull[8];
extern Vtx medusagate_Plane_mesh_layer_4_vtx_0[4];
extern Gfx medusagate_Plane_mesh_layer_4_tri_0[];
extern Gfx mat_medusagate_f3d_material[];
extern Gfx mat_revert_medusagate_f3d_material[];
extern Gfx medusagate_Plane_mesh_layer_4[];
extern Gfx medusagate_material_revert_render_settings[];
