#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/sl/header.h"

#include "levels/sl/unused_cracked_ice/geo.inc.c"
#include "levels/sl/unused_ice_shard/geo.inc.c"
#include "levels/sl/snow_mound/geo.inc.c"
#include "levels/sl/areas/1/geo.inc.c"
#include "levels/sl/areas/2/geo.inc.c"
#include "levels/sl/geo.inc.c"

#include "levels/sl/namekfloaty/geo.inc.c"
#include "levels/sl/namekElder/geo.inc.c"
#include "levels/sl/namekian/geo.inc.c"
#include "levels/sl/walutroopa/geo.inc.c"
#include "levels/sl/kiattack/geo.inc.c"
#include "levels/sl/bulma/geo.inc.c"
#include "levels/sl/dragonball/geo.inc.c"
#include "levels/sl/dragonball2/geo.inc.c"
#include "levels/sl/dragonball3/geo.inc.c"
#include "levels/sl/dragonball4/geo.inc.c"
#include "levels/sl/dragonball5/geo.inc.c"
#include "levels/sl/dragonball6/geo.inc.c"
#include "levels/sl/dragonball7/geo.inc.c"
#include "levels/sl/waluFreezF1/geo.inc.c"
#include "levels/sl/kaioplanet/geo.inc.c"
#include "levels/sl/deathbeam/geo.inc.c"
#include "levels/sl/waluFreezF2/geo.inc.c"