#include "src/game/envfx_snow.h"

const GeoLayout articuno_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(1, 0, 61, -33, 73, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, articuno_lombar_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, articuno_body_skinned),
				GEO_TRANSLATE_ROTATE(1, 0, 41, 0, 48, -180, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, articuno_body_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, articuno_chest_skinned),
						GEO_TRANSLATE_ROTATE(1, 0, 38, -14, -166, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, articuno_chest_mesh),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(1, articuno_head_skinned),
						GEO_TRANSLATE_ROTATE(1, 0, 34, 0, 15, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, articuno_head_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, articuno_crystal_L_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 26, -13, -49, 78, 57),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_crystal_L_mesh),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(1, articuno_crystal_R_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 26, -13, -49, -78, -57),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_crystal_R_mesh),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(1, articuno_topCrystal_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 26, -13, 52, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_topCrystal_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, -10, 31, 15, 177, 0, 92),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, articuno_wing1_L_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, articuno_wing2_L_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 43, 0, -4, 180, -12),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_wing2_L_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, articuno_wing3_L_skinned),
										GEO_TRANSLATE_ROTATE(1, 0, 57, 0, 5, 2, 18),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_wing3_L_mesh),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, 10, 31, 15, 177, 0, -92),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, articuno_wing1_R_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, articuno_wing2_R_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 43, 0, -4, -180, 12),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_wing2_R_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, articuno_wing3_R_skinned),
										GEO_TRANSLATE_ROTATE(1, 0, 57, 0, 5, -2, -18),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_wing3_R_mesh),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, -5, -2, -179, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, articuno_tail1_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, articuno_tail4_skinned),
						GEO_TRANSLATE_ROTATE(1, 0, 113, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, articuno_tail4_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, articuno_tail7_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 114, 0, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_tail7_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(1, articuno_upperLeg_L_skinned),
				GEO_TRANSLATE_ROTATE(1, 12, 31, 12, 137, 54, 45),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, articuno_upperLeg_L_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, articuno_downLeg_L_skinned),
						GEO_TRANSLATE_ROTATE(1, 0, 23, 0, 2, 126, -25),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, articuno_downLeg_L_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, articuno_foot_L_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 17, 0, -44, -98, 4),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_foot_L_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, articuno_innerFinger1_L_skinned),
										GEO_TRANSLATE_ROTATE(1, -3, 7, 0, 5, -46, 33),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_innerFinger1_L_mesh),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, articuno_middleFinger1_L_skinned),
										GEO_TRANSLATE_ROTATE(1, 0, 7, 0, -7, -69, 25),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_middleFinger1_L_mesh),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, articuno_outFinger1_L_skinned),
										GEO_TRANSLATE_ROTATE(1, 4, 7, 0, -41, -56, 3),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_outFinger1_L_mesh),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, articuno_thumb1_L_skinned),
										GEO_TRANSLATE_ROTATE(1, 0, 0, 2, 115, -2, -2),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_thumb1_L_mesh),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(1, articuno_upperLeg_R_skinned),
				GEO_TRANSLATE_ROTATE(1, -12, 31, 12, 137, -54, -45),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, articuno_upperLeg_R_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, articuno_downLeg_R_skinned),
						GEO_TRANSLATE_ROTATE(1, 0, 23, 0, 2, -126, 25),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, articuno_downLeg_R_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, articuno_foot_R_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 17, 0, -44, 98, -4),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, articuno_foot_R_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, articuno_innerFinger1_R_skinned),
										GEO_TRANSLATE_ROTATE(1, 3, 7, 0, 5, 46, -33),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_innerFinger1_R_mesh),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, articuno_middleFinger1_R_skinned),
										GEO_TRANSLATE_ROTATE(1, 0, 7, 0, -7, 69, -25),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_middleFinger1_R_mesh),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, articuno_outFinger1_R_skinned),
										GEO_TRANSLATE_ROTATE(1, -4, 7, 0, -41, 56, -3),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_outFinger1_R_mesh),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, articuno_thumb1_R_skinned),
										GEO_TRANSLATE_ROTATE(1, 0, 0, 2, 115, 2, 2),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, articuno_thumb1_R_mesh),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, articuno_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, articuno_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, articuno_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, articuno_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, articuno_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, articuno_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, articuno_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, articuno_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
