#include "src/game/envfx_snow.h"

const GeoLayout onix_geo[] = {
   GEO_CULLING_RADIUS(2000),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 228, 1011, 23, -92, -95),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_chest_mesh),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 7, -3, 8, 160, 95, 8),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body1_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 119, 0, -19, 26, 2),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body2_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 88, 0, -2, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body3_mesh),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 126, 0, 16, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body4_mesh),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 100, 0, 14, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body5_mesh),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 113, 0, -1, 0, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body6_mesh),
															GEO_OPEN_NODE(),
																GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 91, 0, -2, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body7_mesh),
																	GEO_OPEN_NODE(),
																		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 115, 0, 5, 0, 0),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body8_mesh),
																			GEO_OPEN_NODE(),
																				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 81, 0, 2, 0, 0),
																				GEO_OPEN_NODE(),
																					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body9_mesh),
																					GEO_OPEN_NODE(),
																						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 132, 0, 28, 0, 0),
																						GEO_OPEN_NODE(),
																							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_body10_mesh),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 116, 5, 19, 59, -4),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_head_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 53, 37, -3, 0, -1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onix_mouth_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, onix_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
