extern const GeoLayout dragonball_geo[];
extern u8 dragonball__1dbea000_fmt0433_slice0_mip00_64x64_tm04_rgba32[];
extern u8 dragonball_Unbenannt_1_rgba16[];
extern Vtx dragonball_Icosphere_mesh_layer_5_vtx_cull[8];
extern Vtx dragonball_Icosphere_mesh_layer_5_vtx_0[90];
extern Gfx dragonball_Icosphere_mesh_layer_5_tri_0[];
extern Vtx dragonball_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx dragonball_Plane_mesh_layer_5_vtx_0[4];
extern Gfx dragonball_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_dragonball_f3d_material[];
extern Gfx mat_revert_dragonball_f3d_material[];
extern Gfx mat_dragonball_f3d_material_001[];
extern Gfx mat_revert_dragonball_f3d_material_001[];
extern Gfx dragonball_Icosphere_mesh_layer_5[];
extern Gfx dragonball_Plane_mesh_layer_5[];
extern Gfx dragonball_material_revert_render_settings[];
