#include "src/game/envfx_snow.h"

const GeoLayout thi_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_cause_env_lightning),
		GEO_ASM(LAYER_TRANSPARENT_DECAL, geo_cause_env_lightning),
		GEO_ASM(7, geo_render_INFBG),
		GEO_ASM(8, geo_render_INFBG),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_AAAPlane_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, thi_dl_AAAPlane_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, thi_dl_AAAPlane_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_AAAPlane_mesh_layer_4),
		GEO_ASM(1, geo_cause_env_lightning),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -152, 370, -427),
		GEO_ASM(2, geo_cause_env_lightning),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -505, 372, -187),
		GEO_ASM(3, geo_cause_env_lightning),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -452, 372, 294),
		GEO_ASM(4, geo_cause_env_lightning),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -845, 372, 6),
		GEO_ASM(5, geo_cause_env_lightning),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1069, 372, -324),
		GEO_ASM(6, geo_cause_env_lightning),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1257, 372, 21),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_OCEAN_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, thi_dl_OceanDecal_mesh_layer_6),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 6339, 4901, 0, thi_dl_Zail_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 6429, 2666, 0, thi_dl_Zail_001_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 228, 5919, 0, thi_dl_Zail_002_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 269, 2535, 0, thi_dl_Zail_003_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -4172, 6247, 0, thi_dl_Zail_004_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -4159, 3985, 0, thi_dl_Zail_005_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout thi_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0043),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 133, 40000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -1, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, thi_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_RAIN, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
