#include "src/game/envfx_snow.h"

const GeoLayout panther_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 1, 0, panther_Belly_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, panther_Chest_skinned),
			GEO_TRANSLATE_ROTATE(1, 0, 104, 0, -4, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, panther_Chest_mesh),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(1, 0, 150, 0, -121, -97, 9),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, panther_L_Shoulder_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, panther_L_UpperArm_skinned),
							GEO_TRANSLATE_ROTATE(1, 0, 49, 0, 28, 0, -2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, panther_L_UpperArm_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, panther_L_LowerArm_skinned),
									GEO_TRANSLATE_ROTATE(1, 0, 135, 0, -2, 0, 3),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 0, 0, panther_L_LowerArm_mesh),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(1, 0, 120, 0, -4, 0, -1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, panther_L_Hand_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(1, panther_Neck_skinned),
					GEO_TRANSLATE_ROTATE(1, 0, 150, 0, 1, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, panther_Neck_mesh),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(1, 0, 53, 0, 66, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, panther_Head_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(1, 0, 150, 0, -120, 98, -9),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, panther_R_Shoulder_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, panther_R_UpperArm_skinned),
							GEO_TRANSLATE_ROTATE(1, 0, 49, 0, 27, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, panther_R_UpperArm_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, panther_R_LowerArm_skinned),
									GEO_TRANSLATE_ROTATE(1, 0, 121, 0, -2, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 0, 0, panther_R_LowerArm_mesh),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(1, 0, 140, 0, -4, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, panther_R_Hand_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(1, 19, -4, -7, 179, 36, -2),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, panther_L_UpperLeg_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, panther_L_LowerLeg_skinned),
					GEO_TRANSLATE_ROTATE(1, 0, 135, 0, 1, 126, -1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, panther_L_LowerLeg_mesh),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(1, 0, 162, 0, 80, 73, -12),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(1, -19, -4, -7, -178, 36, 2),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, panther_R_UpperLeg_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, panther_R_LowerLeg_skinned),
					GEO_TRANSLATE_ROTATE(1, 0, 135, 0, 0, 126, -1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, panther_R_LowerLeg_mesh),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(1, 0, 162, 0, 80, 104, 9),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, panther_R_Feet_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(1, -1, 41, -22, -71, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, panther_Tail1_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(1, panther_Tail4_skinned),
					GEO_TRANSLATE_ROTATE(1, 0, 94, 0, 37, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, panther_Tail4_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, panther_Tail7_skinned),
							GEO_TRANSLATE_ROTATE(1, 0, 130, 0, -94, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, panther_Tail7_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, panther_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, panther_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, panther_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, panther_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, panther_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, panther_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, panther_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, panther_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
