extern const GeoLayout blackthwomp_Bone_opt1[];
extern const GeoLayout blackthwomp_Bone_opt2[];
extern const GeoLayout blackthwomp_Bone_opt3[];
extern const GeoLayout blackthwomp_Bone_opt4[];
extern const GeoLayout blackthwomp_Bone_opt5[];
extern const GeoLayout blackthwomp_Bone_opt6[];
extern const GeoLayout blackthwomp_Bone_opt7[];
extern const GeoLayout blackthwomp_geo[];
extern Lights1 blackthwomp_BlackPattern_v4_lights;
extern Lights1 blackthwomp_K_Club_v4_lights;
extern Lights1 blackthwomp_Q_Club_v4_lights;
extern Lights1 blackthwomp_J_Club_v4_lights;
extern Lights1 blackthwomp_A_Club_v4_lights;
extern Lights1 blackthwomp_K_Spades_v4_lights;
extern Lights1 blackthwomp_Q_Spades_v4_lights;
extern Lights1 blackthwomp_J_Spades_v4_lights;
extern Lights1 blackthwomp_A_Spades_v4_lights;
extern u8 blackthwomp_blackPattern_i8[];
extern u8 blackthwomp_K_Club_ci4[];
extern u8 blackthwomp_K_Club_ci4_pal_rgba16[];
extern u8 blackthwomp_Q_Club_ci4[];
extern u8 blackthwomp_Q_Club_ci4_pal_rgba16[];
extern u8 blackthwomp_J_Club_ci4[];
extern u8 blackthwomp_J_Club_ci4_pal_rgba16[];
extern u8 blackthwomp_A_Club_ci4[];
extern u8 blackthwomp_A_Club_ci4_pal_rgba16[];
extern u8 blackthwomp_K_Spades_ci4[];
extern u8 blackthwomp_K_Spades_ci4_pal_rgba16[];
extern u8 blackthwomp_Q_Spades_ci4[];
extern u8 blackthwomp_Q_Spades_ci4_pal_rgba16[];
extern u8 blackthwomp_J_Spades_ci4[];
extern u8 blackthwomp_J_Spades_ci4_pal_rgba16[];
extern u8 blackthwomp_A_Spades_ci4[];
extern u8 blackthwomp_A_Spades_ci4_pal_rgba16[];
extern Vtx blackthwomp_Bone_001_mesh_layer_1_vtx_0[48];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_tri_0[];
extern Vtx blackthwomp_Bone_001_mesh_layer_1_vtx_1[29];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_tri_1[];
extern Gfx mat_blackthwomp_BlackPattern_v4[];
extern Gfx mat_blackthwomp_K_Club_v4[];
extern Gfx mat_revert_blackthwomp_K_Club_v4[];
extern Gfx mat_blackthwomp_Q_Club_v4[];
extern Gfx mat_revert_blackthwomp_Q_Club_v4[];
extern Gfx mat_blackthwomp_J_Club_v4[];
extern Gfx mat_revert_blackthwomp_J_Club_v4[];
extern Gfx mat_blackthwomp_A_Club_v4[];
extern Gfx mat_revert_blackthwomp_A_Club_v4[];
extern Gfx mat_blackthwomp_K_Spades_v4[];
extern Gfx mat_revert_blackthwomp_K_Spades_v4[];
extern Gfx mat_blackthwomp_Q_Spades_v4[];
extern Gfx mat_revert_blackthwomp_Q_Spades_v4[];
extern Gfx mat_blackthwomp_J_Spades_v4[];
extern Gfx mat_revert_blackthwomp_J_Spades_v4[];
extern Gfx mat_blackthwomp_A_Spades_v4[];
extern Gfx mat_revert_blackthwomp_A_Spades_v4[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_mat_override_Q_Club_v4_0[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_mat_override_J_Club_v4_1[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_mat_override_A_Club_v4_2[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_mat_override_K_Spades_v4_3[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_mat_override_Q_Spades_v4_4[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_mat_override_J_Spades_v4_5[];
extern Gfx blackthwomp_Bone_001_mesh_layer_1_mat_override_A_Spades_v4_6[];
extern Gfx blackthwomp_material_revert_render_settings[];
