#include "src/game/envfx_snow.h"

const GeoLayout quetzl_geo[] = {
   GEO_CULLING_RADIUS(2000),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -4, 106, 0, -90, 88),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_head_mesh),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 156, 0, -2, 90, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_tail1_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 90, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_tail2_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 98, 0, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_tail3_mesh),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 31, 66, 23, -120, -121, -5),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_WingBase_L_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, quetzl_Wing2_L_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 65, 0, 46, -79, -18),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_Wing2_L_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, quetzl_Wing3_L_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 79, 0, -20, 56, -19),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_Wing3_L_mesh),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, quetzl_Wing4_L_skinned),
																GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 29, -10, 16),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_Wing4_L_mesh),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -31, 66, 23, -120, 121, 5),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_WingBase_R_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, quetzl_Wing2_R_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 65, 0, 46, 79, 18),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_Wing2_R_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, quetzl_Wing3_R_skinned),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 79, 0, -20, -56, 19),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_Wing3_R_mesh),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, quetzl_Wing4_R_skinned),
																GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 29, 10, -16),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_Wing4_R_mesh),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 106, 0, 2, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_tail4_mesh),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 97, 0, -1, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_tail5_mesh),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 89, 0, quetzl_tail6_mesh),
														GEO_OPEN_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -18, 98, -11, -35, -6, 42),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_UpperLeg_R_mesh),
																GEO_OPEN_NODE(),
																	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 38, 0, 73, -63, 104),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_LowerLeg_R_mesh),
																		GEO_OPEN_NODE(),
																			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 42, 0, 34, 24, 2),
																			GEO_OPEN_NODE(),
																				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_Hand_R_mesh),
																				GEO_OPEN_NODE(),
																					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 30, 0, 16, 40, 13),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_MiddleFinger1_R_mesh),
																						GEO_OPEN_NODE(),
																							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 19, 0, -26, -78, 18),
																							GEO_OPEN_NODE(),
																								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_MiddleFinger2_R_mesh),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 21, -1, 64, 93, 28),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_PinkyFinger1_R_mesh),
																						GEO_OPEN_NODE(),
																							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 14, 0, 4, 177, 50),
																							GEO_OPEN_NODE(),
																								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_PinkyFinger2_R_mesh),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -11, 19, -1, -1, 27, 67),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_Thumb1_R_mesh),
																						GEO_OPEN_NODE(),
																							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -47, -49, 20),
																							GEO_OPEN_NODE(),
																								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_Thumb2_R_mesh),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 92, 0, quetzl_tail7_mesh),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 93, 0, quetzl_tail8_mesh),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 87, 0, quetzl_tail9_mesh),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 71, 0, quetzl_tail10_mesh),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 70, 0, quetzl_tail11_mesh),
																			GEO_OPEN_NODE(),
																				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 78, 0, -1, 0, 0),
																				GEO_OPEN_NODE(),
																					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_tail12_mesh),
																					GEO_OPEN_NODE(),
																						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 74, 0, 1, 0, 0),
																						GEO_OPEN_NODE(),
																							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, quetzl_tail13_mesh),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 17, 98, -11, -42, -6, -34),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_upperLeg_L_mesh),
																GEO_OPEN_NODE(),
																	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 38, 0, 29, 86, -95),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_LowerLeg_L_mesh),
																		GEO_OPEN_NODE(),
																			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 42, 0, 34, 20, -3),
																			GEO_OPEN_NODE(),
																				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_HandL_mesh),
																				GEO_OPEN_NODE(),
																					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 30, 0, 17, 38, 13),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_MiddleFinger1_L_mesh),
																						GEO_OPEN_NODE(),
																							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 19, 0, -24, -76, 21),
																							GEO_OPEN_NODE(),
																								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_MiddleFinger2_L_mesh),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 21, -1, 8, 25, 67),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_PinkyFinger1_L_mesh),
																						GEO_OPEN_NODE(),
																							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 14, 0, -50, -17, 10),
																							GEO_OPEN_NODE(),
																								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_PinkyFinger2_L_mesh),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 11, 19, -1, 64, 90, 24),
																					GEO_OPEN_NODE(),
																						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_Thumb1_L_mesh),
																						GEO_OPEN_NODE(),
																							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 7, -176, 49),
																							GEO_OPEN_NODE(),
																								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, quetzl_Thumb2_L_mesh),
																							GEO_CLOSE_NODE(),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, quetzl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, quetzl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
