extern const GeoLayout lampfire_geo[];
extern Vtx lampfire_Bone_mesh_vtx_0[99];
extern Gfx lampfire_Bone_mesh_tri_0[];
extern Vtx lampfire_Bone_mesh_vtx_1[5];
extern Gfx lampfire_Bone_mesh_tri_1[];
extern Vtx lampfire_Bone_mesh_vtx_2[6];
extern Gfx lampfire_Bone_mesh_tri_2[];
extern Vtx lampfire_Bone_mesh_vtx_3[16];
extern Gfx lampfire_Bone_mesh_tri_3[];
extern Vtx lampfire_Bone_002_mesh_vtx_0[24];
extern Gfx lampfire_Bone_002_mesh_tri_0[];
extern Vtx lampfire_Bone_003_mesh_vtx_0[8];
extern Gfx lampfire_Bone_003_mesh_tri_0[];
extern Vtx lampfire_Bone_003_mesh_vtx_1[20];
extern Gfx lampfire_Bone_003_mesh_tri_1[];
extern Vtx lampfire_Bone_003_skinned_vtx_0[8];
extern Gfx lampfire_Bone_003_skinned_tri_0[];
extern Vtx lampfire_Bone_004_mesh_vtx_0[16];
extern Gfx lampfire_Bone_004_mesh_tri_0[];
extern Vtx lampfire_Bone_004_mesh_vtx_1[32];
extern Gfx lampfire_Bone_004_mesh_tri_1[];
extern Vtx lampfire_Bone_005_mesh_vtx_0[8];
extern Gfx lampfire_Bone_005_mesh_tri_0[];
extern Vtx lampfire_Bone_006_mesh_vtx_0[12];
extern Gfx lampfire_Bone_006_mesh_tri_0[];
extern Vtx lampfire_Bone_006_mesh_vtx_1[8];
extern Gfx lampfire_Bone_006_mesh_tri_1[];

extern Gfx lampfire_Bone_mesh[];
extern Gfx lampfire_Bone_002_mesh[];
extern Gfx lampfire_Bone_003_mesh[];
extern Gfx lampfire_Bone_003_skinned[];
extern Gfx lampfire_Bone_004_mesh[];
extern Gfx lampfire_Bone_005_mesh[];
extern Gfx lampfire_Bone_006_mesh[];
extern Gfx lampfire_material_revert_render_settings[];

