#include "src/game/envfx_snow.h"

const GeoLayout tangela_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(4, 0, 0, 0, tangela_head_mesh),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(1, 22, 42, -2, -171, -4, 3),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(1, 0, 50, 0, 94, 136, -39),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, tangela_foot_L_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(1, -23, 42, -2, -171, -4, -2),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(1, 0, 50, 0, 86, 36, -141),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, tangela_foot_R_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, tangela_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, tangela_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, tangela_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, tangela_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, tangela_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, tangela_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, tangela_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, tangela_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
