#include "src/game/envfx_snow.h"

const GeoLayout gyarados_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 144, 75, 17, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_neck_mesh),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 168, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body1_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 47, 0, -1, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body2_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 56, 0, 13, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body3_mesh),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 63, 0, 44, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body4_mesh),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 77, 0, 31, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body5_mesh),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 79, 0, 7, 0, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body6_mesh),
															GEO_OPEN_NODE(),
																GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 67, 0, 1, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body7_mesh),
																	GEO_OPEN_NODE(),
																		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 63, 0, -2, 0, 0),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body8_mesh),
																			GEO_OPEN_NODE(),
																				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 69, 0, 2, 0, 0),
																				GEO_OPEN_NODE(),
																					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body9_mesh),
																					GEO_OPEN_NODE(),
																						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 64, 0, -1, 0, 0),
																						GEO_OPEN_NODE(),
																							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_body10_mesh),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 59, 0, -74, -180, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_head_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -43, 94, -20, 0, -2, 128),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_fin_L_mesh),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 43, 94, -20, 0, 2, -128),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_fin_R_mesh),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -38, 111, -51, 5, -43, 101),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_moustache_L_mesh),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 38, 111, -51, 5, 43, -101),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gyarados_moustache_R_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gyarados_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
