#include "src/game/envfx_snow.h"

const GeoLayout noseguy_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -12, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_head_mesh),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 279, 0, -9, 88, -162),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 302, 0, -100, -28, -62),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_Foot_L_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 279, 0, -9, -88, 162),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(4, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 302, 0, -100, 27, 63),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_Foot_R_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(1, 77, 119, 1, 109, 107, 3),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_UpperArm_L_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 32, 0, -15, 15, 9),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_LowerArm_L_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 31, 0, 2, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_Hand_L_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(1, -74, 119, 1, -16, -19, 110),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_UpperArm_R_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 32, 0, 15, 59, 9),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_LowerArm_R_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 31, 0, -2, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, noseguy_Hand_R_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, noseguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, noseguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, noseguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, noseguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, noseguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, noseguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, noseguy_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, noseguy_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
