#include "src/game/envfx_snow.h"

const GeoLayout jrb_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, -2605, 0, jrb_dl_Aearth_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, -2605, 0, jrb_dl_Bwater_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, -2605, 0, jrb_dl_Cwaterfall_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 0, -2605, 0, jrb_dl_deathplanealpha_001_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 0, -2605, 0, jrb_dl_deathplanealpha_002_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, -2605, 0, jrb_dl_deathplaneopaque_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_deathplaneopaque_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, -2605, 0, jrb_dl_deathplaneopaque_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_deathplaneopaque_001_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 0, -2605, 0, jrb_dl_deathplaneopaque_002_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 3173, 974, 1003, 90, 0, 77, jrb_dl_DKStatue_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 431, -2391, 197, jrb_dl_Dwaterfall_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_fLOWERbUSH1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_fLOWERbUSH1_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -368, 349, 4225, 90, 0, 0, jrb_dl_fountain1_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -368, 349, 4225, 90, 0, 0, jrb_dl_fountain1_001_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -2298, 3268, -1996, 90, 0, -90, jrb_dl_pALMtREE_001_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2911, 1770, 3410, 0, -180, 0, jrb_dl_pillar12_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_Plane_024_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_poles_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_terrain_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jrb_dl_terrain_001_mesh_layer_5),
		GEO_TRANSLATE_NODE(LAYER_ALPHA, -648, -939, -129),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 22, 320, 1291, jrb_dl_water_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -1216, 2436, 705, 90, 0, 0, jrb_dl_yoshiStatue1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -1, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, jrb_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jrb_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
