extern const GeoLayout bitdw_area_1_geo[];
extern const GeoLayout bitdw_area_1[];
extern const Collision bitdw_area_1_collision[];
extern const MacroObject bitdw_area_1_macro_objs[];
extern const GeoLayout bitdw_area_2_geo[];
extern const GeoLayout bitdw_area_2[];
extern const Collision bitdw_area_2_collision[];
extern const MacroObject bitdw_area_2_macro_objs[];
extern Lights1 bitdw_dl_f3d_material_007_lights;
extern Lights1 bitdw_dl_Digimat_layer1_lights;
extern Lights1 bitdw_dl_f3d_material_004_layer1_lights;
extern u8 bitdw_dl_rrow_asset_1414_i4[];
extern u8 bitdw_dl_pattern_i4[];
extern u8 bitdw_dl_Unbenannt_i4[];
extern Vtx bitdw_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx bitdw_dl_Circle_mesh_layer_1_vtx_0[259];
extern Gfx bitdw_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bitdw_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bitdw_dl_Plane_mesh_layer_1_vtx_0[877];
extern Gfx bitdw_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bitdw_dl_Circle_002_mesh_layer_1_vtx_cull[8];
extern Vtx bitdw_dl_Circle_002_mesh_layer_1_vtx_0[259];
extern Gfx bitdw_dl_Circle_002_mesh_layer_1_tri_0[];
extern Vtx bitdw_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx bitdw_dl_Plane_001_mesh_layer_1_vtx_0[973];
extern Gfx bitdw_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_bitdw_dl_f3d_material_007[];
extern Gfx mat_revert_bitdw_dl_f3d_material_007[];
extern Gfx mat_bitdw_dl_Digimat_layer1[];
extern Gfx mat_revert_bitdw_dl_Digimat_layer1[];
extern Gfx mat_bitdw_dl_f3d_material_004_layer1[];
extern Gfx mat_revert_bitdw_dl_f3d_material_004_layer1[];
extern Gfx bitdw_dl_Circle_mesh_layer_1[];
extern Gfx bitdw_dl_Plane_mesh_layer_1[];
extern Gfx bitdw_dl_Circle_002_mesh_layer_1[];
extern Gfx bitdw_dl_Plane_001_mesh_layer_1[];
extern Gfx bitdw_dl_material_revert_render_settings[];
