enum ShyguycaptainAnims {
	SHYGUYCAPTAIN_ANIM_IDLE_PIANO,
	SHYGUYCAPTAIN_ANIM_IDLE_PIANO_TALKTOMARIO_TOFIGHT,
	SHYGUYCAPTAIN_ANIM_IDLE_FIGHT,
	SHYGUYCAPTAIN_ANIM_SPIN_ATTACK,
	SHYGUYCAPTAIN_ANIM_FLAME_ATTACK,
	SHYGUYCAPTAIN_ANIM_DAMAGED,
	SHYGUYCAPTAIN_ANIM_DASH_TO_PIANO,
	SHYGUYCAPTAIN_ANIMS_END,
};
