COURSE_ACTS(COURSE_BOB, _(" 1 EL DORADO"),//0
       _("TO THE TEMPLE TOP")     , _("FLIPPING THE TILES") , _("ROCK RACE RUSH"),
       _("SCARY BLOCK STAIRCASE")          , _("ANCIENT RED GOLD")        , _("CATCH THE QUETZACOATL"))

COURSE_ACTS(COURSE_WF, _(" 2 SHIPWRECK COVE"),//1
       _("EXPLORE THE WRECK")        , _("BOB OMB PIRATE BATTLE")    , _("HAUNTERS HAUNTING SKILL"),
       _("THE GOLD STASH"), _("CRIMSON COIN COLLECTION")    , _("THE SHARKS TREASURE"))

COURSE_ACTS(COURSE_JRB, _(" 3 BABYLON"),//3
       _("PLUCK THE PIRANHAS")    , _("SWING ON THE VINES") , _("THE HIDDEN ENTRANCE"),
       _("CLIMB THE BEANSTALK")  , _("REDS ON THE DOCKS")     , _("THE HANGING GARDEN"))

COURSE_ACTS(COURSE_CCM, _(" 4 EGYPT"),//6
       _("THE MYSTERY OF THE TOMB")             , _("CRACKING THE OASIS")             , _("THE OLD PHARAOH"),
       _("CANYON CHAPEL CLIMB")  , _("THE NILE'S RED COINS")       , _("MADDENING MIRAGE"))

COURSE_ACTS(COURSE_BBH, _(" 5 COLOSSUS OF DK"),//10
       _("THE ANCIENT GAME")            , _("KOOPAS SURF CHALLENGE") , _("SHOOT TO THE STATUE"),
       _("THE SEWER SECRET")          , _("8 RED COINS IN THE HARBOR")             , _("HAUNTERS HEIST"))

COURSE_ACTS(COURSE_HMC, _(" 6 TIKI ISLAND"),//15
       _("VOLCANO ADVENTURE")  , _("TIKI-GUY TOTEMPOLE")       , _("TIKITOWN TREASURE"),
       _("THE BACK OF THE TOWN")     , _("RED COIN RODEO")     , _("EASTER HEAD TROUBLE"))

COURSE_ACTS(COURSE_LLL, _(" 7 THE GREAT WALL"),//20
       _("THE GREAT CLIMB")            , _("PUZZLING PAGODA")             , _("THE TOWER TROOPER"),
       _("THE LONGEST SLIDE")           , _("RED TOWER TREASURE")  , _("AWAKEN THE DRAGON"))

COURSE_ACTS(COURSE_SSL, _(" 8 20000 MILES UNDER THE SEA"),//25
       _("THE KRAKENS GEM") , _("THE SUNKEN NAUTILUS")      , _("DEEP SEA TREASURE"),
       _("ANGLERFISH BAIT"), _("RED COIN KELP FOREST")   , _("FISH MOMMY'S WARD"))

COURSE_ACTS(COURSE_DDD, _(" 9 THE OLYMP"),//30
       _("ZEUS' HATBOY")            , _("LUIGI'S RACEWAY")         , _("WARIO'S WINE"),
       _("RAINBOW'S PATH")        , _("ZEUS' DOWNFALL")        , _("GREEK'S REDS"))

COURSE_ACTS(COURSE_SL, _("10 PLANET NAMEK"),//35
       _("SAVE THE VILLAGE")            , _("FIND THE SCIENTIST")          , _("FIND THE DRAGON BALLS"),
       _("SNEAK INTO THE SHIP")  , _("THE OTHER WORLD") , _("MARIO, THE SUPER PLUMBER"))

COURSE_ACTS(COURSE_WDW, _("11 DANDYWORLD"),//42
       _("NO TIME!")         , _("FOUR OF A KIND")               , _("STOLEN SILVERWARE"),
       _("WHERE NOONE LOOKS")   , _("URGH CASTLE")      , _("TUM TUM TROUBLE"))

COURSE_ACTS(COURSE_TTM, _("12 TALL, TALL MOUNTAIN"),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE MONKEY CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 TINY-HUGE ISLAND"),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH KOOPA THE QUICK"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 TICK TOCK CLOCK"),
       _("ROLL INTO THE CAGE")            , _("THE PIT AND THE PENDULUMS")     , _("GET A HAND"),
       _("STOMP ON THE THWOMP")           , _("TIMED JUMPS ON MOVING BARS")    , _("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 RAINBOW RIDE"),
       _("CRUISER CROSSING THE RAINBOW")  , _("THE BIG HOUSE IN THE SKY")      , _("COINS AMASSED IN A MAZE"),
       _("SWINGIN' IN THE BREEZE")        , _("TRICKY TRIANGLES!")             , _("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(COURSE_BITDW, _("   POKEMON CHALLENGE"))
SECRET_STAR(COURSE_BITFS, _("   POKEMON CHALLENGE"))
SECRET_STAR(COURSE_BITS, _("   THE COURT"))
SECRET_STAR(COURSE_PSS, _("   THE PRINCESS'S SECRET SLIDE"))
SECRET_STAR(COURSE_COTMC, _("   CAVERN OF THE METAL CAP"))
SECRET_STAR(COURSE_TOTWC, _("   TOWER OF THE WING CAP"))
SECRET_STAR(COURSE_VCUTM, _("   VANISH CAP UNDER THE MOAT"))
SECRET_STAR(COURSE_WMOTR, _("   WING MARIO OVER THE RAINBOW"))
SECRET_STAR(COURSE_SA, _("   THE SECRET AQUARIUM"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   CASTLE SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE CASTLE'S SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
