#include "src/game/envfx_snow.h"

const GeoLayout wingo_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 120, -12, 37, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_body_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_head_skinned_mesh_layer_1),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 107, 0, 23, -180, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_head_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_head_mesh_layer_4),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_mouth_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 2, -43, -75, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_mouth_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 43, -42, 22, 138, 1, 3),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_leg_L_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_foot_L_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 69, 0, 74, -172, 10),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_foot_L_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -43, -42, 22, 138, -1, -3),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_leg_R_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_foot_R_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 69, 0, 74, 172, -10),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_foot_R_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -63, -90, -130, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wingo_tail_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 78, -5, 44, 164, 61),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_wing1_L_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_wing1_L_mesh_layer_4),
						GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_wing2_L_skinned_mesh_layer_4),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_wing2_L_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 89, 0, 12, 104, -9),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wingo_wing2_L_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_wing2_L_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_wing3_L_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 138, 0, 1, -2, 1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wingo_wing3_L_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, 78, -5, 44, -164, -61),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_wing1_R_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_wing1_R_mesh_layer_4),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_wing2_R_skinned_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_wing2_R_skinned_mesh_layer_4),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 89, 0, 12, -104, 9),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wingo_wing2_R_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_wing2_R_mesh_layer_4),
								GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_wing3_R_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 138, 0, 1, 2, -1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wingo_wing3_R_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wingo_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, wingo_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
