#include "actors/hypno/texscroll.inc.h"
#include "actors/gyarados/texscroll.inc.h"
#include "actors/golem/texscroll.inc.h"
#include "actors/primeape/texscroll.inc.h"
#include "actors/onix/texscroll.inc.h"
#include "actors/tangelaattack/texscroll.inc.h"
#include "actors/tangela/texscroll.inc.h"
#include "actors/icebeam/texscroll.inc.h"
#include "actors/articuno/texscroll.inc.h"
#include "actors/weezing/texscroll.inc.h"
#include "actors/magnemite/texscroll.inc.h"
#include "actors/haunter/texscroll.inc.h"
#include "actors/staryufountain/texscroll.inc.h"
#include "actors/staryu/texscroll.inc.h"
extern void scroll_textures_group0();
