#include "src/game/envfx_snow.h"

const GeoLayout haunter_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, haunter_head_mesh),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(1, 79, -9, 62, 71, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, haunter_hand_L_mesh),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(1, -79, -9, 62, 71, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, haunter_hand_R_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, haunter_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, haunter_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, haunter_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, haunter_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, haunter_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, haunter_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, haunter_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, haunter_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
