#include "levels/bitfs/area_1/geo.inc.c"
#include "levels/bitfs/area_2/geo.inc.c"
#include "levels/bitfs/area_3/geo.inc.c"
#include "levels/bitfs/area_4/geo.inc.c"
#include "levels/bitfs/area_5/geo.inc.c"
#include "levels/bitfs/area_6/geo.inc.c"
