extern const GeoLayout bitfs_area_1_geo[];
extern const GeoLayout bitfs_area_1[];
extern const Collision bitfs_area_1_collision[];
extern const MacroObject bitfs_area_1_macro_objs[];
extern const GeoLayout bitfs_area_2_geo[];
extern const GeoLayout bitfs_area_2[];
extern const Collision bitfs_area_2_collision[];
extern const MacroObject bitfs_area_2_macro_objs[];
extern const GeoLayout bitfs_area_3_geo[];
extern const GeoLayout bitfs_area_3[];
extern const Collision bitfs_area_3_collision[];
extern const MacroObject bitfs_area_3_macro_objs[];
extern const GeoLayout bitfs_area_4_geo[];
extern const GeoLayout bitfs_area_4[];
extern const Collision bitfs_area_4_collision[];
extern const MacroObject bitfs_area_4_macro_objs[];
extern const GeoLayout bitfs_area_5_geo[];
extern const GeoLayout bitfs_area_5[];
extern const Collision bitfs_area_5_collision[];
extern const MacroObject bitfs_area_5_macro_objs[];
extern const GeoLayout bitfs_area_6_geo[];
extern const GeoLayout bitfs_area_6[];
extern const Collision bitfs_area_6_collision[];
extern const MacroObject bitfs_area_6_macro_objs[];
extern Lights1 bitfs_dl_f3d_material_007_lights;
extern Lights1 bitfs_dl_Digimat_layer1_lights;
extern Lights1 bitfs_dl_f3d_material_004_layer1_lights;
extern Lights1 bitfs_dl_f3d_material_layer1_lights;
extern Lights1 bitfs_dl_f3d_material_001_layer5_lights;
extern Lights1 bitfs_dl_ttest_002_layer1_lights;
extern Lights1 bitfs_dl_ttest_004_layer1_lights;
extern Lights1 bitfs_dl_f3d_material_002_layer1_lights;
extern Lights1 bitfs_dl_ttest_005_layer1_lights;
extern u8 bitfs_dl_rrow_asset_1414_i4[];
extern u8 bitfs_dl_pattern_i4[];
extern u8 bitfs_dl_Unbenannt_i4[];
extern u8 bitfs_dl_unknown_15_i4[];
extern u8 bitfs_dl_jan_t_iwayougantif_rgba16[];
extern Vtx bitfs_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Circle_mesh_layer_1_vtx_0[259];
extern Gfx bitfs_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Plane_mesh_layer_1_vtx_0[876];
extern Gfx bitfs_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Circle_002_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Circle_002_mesh_layer_1_vtx_0[259];
extern Gfx bitfs_dl_Circle_002_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Plane_001_mesh_layer_1_vtx_0[869];
extern Gfx bitfs_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Circle_004_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Circle_004_mesh_layer_1_vtx_0[259];
extern Gfx bitfs_dl_Circle_004_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Plane_004_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Plane_004_mesh_layer_1_vtx_0[2216];
extern Gfx bitfs_dl_Plane_004_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Circle_006_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Circle_006_mesh_layer_1_vtx_0[259];
extern Gfx bitfs_dl_Circle_006_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Plane_005_mesh_layer_5_vtx_cull[8];
extern Vtx bitfs_dl_Plane_005_mesh_layer_5_vtx_0[61];
extern Gfx bitfs_dl_Plane_005_mesh_layer_5_tri_0[];
extern Vtx bitfs_dl_Plane_006_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Plane_006_mesh_layer_1_vtx_0[2104];
extern Gfx bitfs_dl_Plane_006_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Circle_008_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Circle_008_mesh_layer_1_vtx_0[259];
extern Gfx bitfs_dl_Circle_008_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Plane_008_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Plane_008_mesh_layer_1_vtx_0[1616];
extern Gfx bitfs_dl_Plane_008_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Plane_008_mesh_layer_1_vtx_1[8];
extern Gfx bitfs_dl_Plane_008_mesh_layer_1_tri_1[];
extern Vtx bitfs_dl_Circle_010_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Circle_010_mesh_layer_1_vtx_0[259];
extern Gfx bitfs_dl_Circle_010_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_Plane_009_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_Plane_009_mesh_layer_1_vtx_0[777];
extern Gfx bitfs_dl_Plane_009_mesh_layer_1_tri_0[];
extern Gfx mat_bitfs_dl_f3d_material_007[];
extern Gfx mat_revert_bitfs_dl_f3d_material_007[];
extern Gfx mat_bitfs_dl_Digimat_layer1[];
extern Gfx mat_revert_bitfs_dl_Digimat_layer1[];
extern Gfx mat_bitfs_dl_f3d_material_004_layer1[];
extern Gfx mat_revert_bitfs_dl_f3d_material_004_layer1[];
extern Gfx mat_bitfs_dl_f3d_material_layer1[];
extern Gfx mat_revert_bitfs_dl_f3d_material_layer1[];
extern Gfx mat_bitfs_dl_f3d_material_001_layer5[];
extern Gfx mat_revert_bitfs_dl_f3d_material_001_layer5[];
extern Gfx mat_bitfs_dl_ttest_002_layer1[];
extern Gfx mat_revert_bitfs_dl_ttest_002_layer1[];
extern Gfx mat_bitfs_dl_ttest_004_layer1[];
extern Gfx mat_revert_bitfs_dl_ttest_004_layer1[];
extern Gfx mat_bitfs_dl_f3d_material_002_layer1[];
extern Gfx mat_revert_bitfs_dl_f3d_material_002_layer1[];
extern Gfx mat_bitfs_dl_ttest_005_layer1[];
extern Gfx mat_revert_bitfs_dl_ttest_005_layer1[];
extern Gfx bitfs_dl_Circle_mesh_layer_1[];
extern Gfx bitfs_dl_Plane_mesh_layer_1[];
extern Gfx bitfs_dl_Circle_002_mesh_layer_1[];
extern Gfx bitfs_dl_Plane_001_mesh_layer_1[];
extern Gfx bitfs_dl_Circle_004_mesh_layer_1[];
extern Gfx bitfs_dl_Plane_004_mesh_layer_1[];
extern Gfx bitfs_dl_Circle_006_mesh_layer_1[];
extern Gfx bitfs_dl_Plane_005_mesh_layer_5[];
extern Gfx bitfs_dl_Plane_006_mesh_layer_1[];
extern Gfx bitfs_dl_Circle_008_mesh_layer_1[];
extern Gfx bitfs_dl_Plane_008_mesh_layer_1[];
extern Gfx bitfs_dl_Circle_010_mesh_layer_1[];
extern Gfx bitfs_dl_Plane_009_mesh_layer_1[];
extern Gfx bitfs_dl_material_revert_render_settings[];
