#include "src/game/envfx_snow.h"

const GeoLayout ddd_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, 368, 810, 839, -90, 0, 0, ddd_dl_bush1_3_004_mesh),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 6706, 1880, -1163, 0, -90, 0, ddd_dl_bush1_4_001_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 12506, 1880, 37, 0, -90, 0, ddd_dl_bush1_4_002_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 359, 852, 1327, ddd_dl_Circle_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 359, 852, 1327, ddd_dl_Circle_001_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_Circle_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 359, 852, 1327, ddd_dl_Circle_004_mesh_layer_6),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -4527, 1465, -17396, 90, 0, 0, ddd_dl_DrawCall_12_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_DrawCall_12_001_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -6270, 93, -17146, 90, 0, 134, ddd_dl_Peach_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_Plane_001_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 5800, 1000, 1200, ddd_dl_Plane_004_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_Plane_011_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_Plane_012_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -918, -389, 8830, ddd_dl_Plane_013_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_Plane_014_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_Rainbows_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 19150, 713, -7077, ddd_dl_wall1_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1010, 499, -2462, ddd_dl_wall1_005_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x9257),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 50000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -1, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ddd_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, ddd_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
