extern const GeoLayout destroybarrel_Armature_001[];
extern const GeoLayout destroybarrel_Armature_002[];
extern const GeoLayout destroybarrel_Armature_003[];
extern const GeoLayout destroybarrel_Armature_004[];
extern const GeoLayout destroybarrel_geo[];
extern u8 destroybarrel_barrel_side_actor_ci8[];
extern u8 destroybarrel_barrel_side_actor_pal_rgba16[];
extern u8 destroybarrel_barrel_top_actor_ci8[];
extern u8 destroybarrel_barrel_top_actor_pal_rgba16[];
extern Vtx destroybarrel_Bone_001_mesh_layer_1_vtx_0[21];
extern Gfx destroybarrel_Bone_001_mesh_layer_1_tri_0[];
extern Vtx destroybarrel_Bone_001_mesh_layer_1_vtx_1[6];
extern Gfx destroybarrel_Bone_001_mesh_layer_1_tri_1[];
extern Vtx destroybarrel_325_23_mesh_layer_1_vtx_0[21];
extern Gfx destroybarrel_325_23_mesh_layer_1_tri_0[];
extern Vtx destroybarrel_325_23_mesh_layer_1_vtx_1[6];
extern Gfx destroybarrel_325_23_mesh_layer_1_tri_1[];
extern Vtx destroybarrel_fdeshsdfh_fdgsdag_mesh_layer_1_vtx_0[21];
extern Gfx destroybarrel_fdeshsdfh_fdgsdag_mesh_layer_1_tri_0[];
extern Vtx destroybarrel_fdeshsdfh_fdgsdag_mesh_layer_1_vtx_1[6];
extern Gfx destroybarrel_fdeshsdfh_fdgsdag_mesh_layer_1_tri_1[];
extern Vtx destroybarrel_fgdfg_ddgdasg_mesh_layer_1_vtx_0[21];
extern Gfx destroybarrel_fgdfg_ddgdasg_mesh_layer_1_tri_0[];
extern Vtx destroybarrel_fgdfg_ddgdasg_mesh_layer_1_vtx_1[6];
extern Gfx destroybarrel_fgdfg_ddgdasg_mesh_layer_1_tri_1[];
extern Vtx destroybarrel_dsga_dggg_mesh_layer_1_vtx_0[21];
extern Gfx destroybarrel_dsga_dggg_mesh_layer_1_tri_0[];
extern Vtx destroybarrel_dsga_dggg_mesh_layer_1_vtx_1[6];
extern Gfx destroybarrel_dsga_dggg_mesh_layer_1_tri_1[];
extern Gfx mat_destroybarrel_f3d_material_047[];
extern Gfx mat_revert_destroybarrel_f3d_material_047[];
extern Gfx mat_destroybarrel_f3dlite_material_059[];
extern Gfx mat_revert_destroybarrel_f3dlite_material_059[];
extern Gfx destroybarrel_Bone_001_mesh_layer_1[];
extern Gfx destroybarrel_325_23_mesh_layer_1[];
extern Gfx destroybarrel_fdeshsdfh_fdgsdag_mesh_layer_1[];
extern Gfx destroybarrel_fgdfg_ddgdasg_mesh_layer_1[];
extern Gfx destroybarrel_dsga_dggg_mesh_layer_1[];
