#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/rendering_graph_node.h"
#include "game/camera.h"
#include "game/screen_transition.h"

#include "make_const_nonconst.h"

#include "levels/thi/header.h"

#include "levels/thi/geo.inc.c"

#include "levels/thi/lightning/geo.inc.c"
#include "levels/thi/ghostplatform/geo.inc.c"
#include "levels/thi/ghostlantern/geo.inc.c"
#include "levels/thi/destroybarrel/geo.inc.c"
#include "levels/thi/booguybarrell/geo.inc.c"
#include "levels/thi/floorbreak/geo.inc.c"
#include "levels/thi/booguy/geo.inc.c"
#include "levels/thi/jellyblock/geo.inc.c"
#include "levels/thi/paintguy/geo.inc.c"
#include "levels/thi/wallsword/geo.inc.c"
#include "levels/thi/tunnel/geo.inc.c"
#include "levels/thi/tunnel2/geo.inc.c"
#include "levels/thi/chandelier/geo.inc.c"
#include "levels/thi/pushcargobox/geo.inc.c"
#include "levels/thi/pushshelf/geo.inc.c"
#include "levels/thi/ropebridge/geo.inc.c"
#include "levels/thi/crumblefloor/geo.inc.c"
#include "levels/thi/shyguyblock/geo.inc.c"
#include "levels/thi/Shyguysays/geo.inc.c"
#include "levels/thi/guybed/geo.inc.c"
#include "levels/thi/movecrate/geo.inc.c"
#include "levels/thi/rumbottle/geo.inc.c"
#include "levels/thi/shyguycaptain/geo.inc.c"
#include "levels/thi/fallplatform1/geo.inc.c"
#include "levels/thi/fallplatform2/geo.inc.c"
#include "levels/thi/lineplatform/geo.inc.c"
#include "levels/thi/blueflame/geo.inc.c"
#include "levels/thi/retropiranha/geo.inc.c"
#include "levels/thi/Shipcannon/geo.inc.c"
#include "levels/thi/booguybarrell2/geo.inc.c"
#include "levels/thi/booguybarrell3/geo.inc.c"
#include "levels/thi/NewBookend/geo.inc.c"
#include "levels/thi/Catchnet/geo.inc.c"
#include "levels/thi/DoubleDoor/geo.inc.c"
#include "levels/thi/MadPiano/geo.inc.c"
#include "levels/thi/ThePlank/geo.inc.c"
#include "levels/thi/GhostshipDoor/geo.inc.c"
