#include "src/game/envfx_snow.h"

const GeoLayout thi_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(LAYER_OPAQUE, Geo_KillEnvColor),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room1_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, thi_dl_Room2_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, thi_dl_Room2_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, thi_dl_Room2_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room2_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room3_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, thi_dl_Room3_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, thi_dl_Room3_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, thi_dl_Room3_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room5_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, thi_dl_Room5_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room5_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room6_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room6_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room7_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room7_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room8_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room8_mesh_layer_4),
		GEO_ASM(0, geo_render_captain_background),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, thi_dl_Room9_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, thi_dl_Room9_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, thi_dl_Room9_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, thi_dl_Room9_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout thi_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0043),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 75292, 0, -1, 75292, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, thi_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
