#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 3081, -305, 2049, bbh_dl_Cube_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1354, -516, 6597, bbh_dl_Cube_002_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1354, -516, 6597, bbh_dl_Cube_003_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_DKalpha_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Dkstuff_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -479, -38, 2019, bbh_dl_Yacht_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -479, -38, 2019, bbh_dl_Yacht_001_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 6334, -160, 5674, bbh_dl_boat_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_buildings_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_buildings_001_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_buildings_002_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_buildings_004_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_buildings_006_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_buildings_008_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_buildings_010_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 376, 44, 4611, bbh_dl_cruiser_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 376, 44, 4611, bbh_dl_cruiser_001_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 376, 44, 4611, bbh_dl_cruiser_002_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_main_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_main_001_mesh),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_main_002_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_plants_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_windows_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -802, -569, 42, bbh_dl_world_001_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -802, -569, 42, bbh_dl_world_002_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -802, -569, 42, bbh_dl_world_777_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -802, -413, 42, bbh_dl_world_778_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -4559, 336, 5525, bbh_dl_yacht_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -4559, 336, 5525, bbh_dl_yacht_001_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -1, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
